config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  match 'logout' => 'sessions#destroy', via: [:get, :delete]

  get 'signup' => 'users#new'
  post 'signup' => 'users#create'

  resources :users, only: [:edit, :update, :show]

  resources :categories, only: [:index, :show] do |f|
    resources :questions, only: [:index, :update]
    resources :highscore, only: [:update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :questions
  has_many :user_categories
  has_many :users, through: :user_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :check_user, except: [:index]

  def index
    @category = Category.new
    @categories = Category.order('categories.name ASC').all

    respond_to do |format|
      format.html
      format.json {render json: @categories}
    end
  end

  def show
    category_id = params[:id]

    # find if user_category_id already exist
    # user_category = current_category user is at
    user_category = UserCategory.find_by(user_id: current_user[:id], category_id: category_id)
    if user_category == nil
      # create if user_category doesn't exist
      user_category = UserCategory.create(user_id: current_user[:id], category_id: category_id)
    end

    @category = Category.find_by(id: category_id)
    @highscores = UserCategory.order('user_categories.category_exp DESC').where(category_id: category_id)
    # number of questions user completed
    completed_qns = CompletedQuestion.where(user_category_id: user_category.id)
    if completed_qns.empty?
      @completed_qns = []
    else
      @completed_qns = completed_qns
    end
    @user_details = user_category
    @questions = @category.questions.length

    respond_to do |format|
      format.html
      format.json {render json: {
        category: @category,
        highscores: @highscores,
        questions: @questions,
        user_details: @user_details,
        completed_qns: @completed_qns
      }}
    end
  end

  private

  def check_user
    if !current_user
      flash[:danger] = 'Please login in to use the service!'
      redirect_to login_path
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<ul class="breadcrumb">
  <li><%= link_to 'Home',root_path %></li>
  <li><span class="black-text">Categories</span></li>
</ul>

<h2>Categories Galore!</h2>

<div class="row">
  <% @categories.each do |category| %>
    <div class="col s2 m2" id="category_main_card">
      <div class="card">
        <div class="card-image" id="category_main_icons">
          <%= image_tag(category.icon_source) %>
        </div>
      </div>
      <div class="center-align">
        <%= link_to category_path(category.id) do %>
            <p>Enter</p>
        <% end %>
        <p class="category_card_name"><%= category.name %></p>
      </div>
    </div>
  <% end %>
</div>

<script>
  $.getJSON('/categories', function (data) {
    console.log(data)
  })
</script>

app/views/categories/show.html.erb
<!-- questions is the number of questions in the category -->
<!-- completed_qns is the number questions user compeleted -->
<!-- user_details is the user's current exp in that table-->

<ul class="breadcrumb">
  <li><%= link_to 'Home',root_path %></li>
  <li><%= link_to 'Categories',categories_path %></li>
  <li><span class="black-text"><%= @category.name %></span></li>
</ul>

<h2><%= @category.name %></h2>

<div class="row">
  <div class="col s4">
    <div class="card" id="show_user_details">
      <div class="card-image" id="category_card_image">
        <%= image_tag(@category.icon_source, :class => "category_icon") %>
      </div>
      <div class="card-content">
        <span class="card-title">Your stats:</span>
        <table class="centered">
          <thead>
            <tr>
              <th>Completed</th>
              <th>Total Qns</th>
              <th>Exp</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @completed_qns.length %></td>
              <td><%= @questions %></td>
              <td><%= @user_details.category_exp %></td>
            </tr>
          </tbody>
        </table>
        <%= link_to category_questions_path(@category.id), class: "waves-effect waves-light btn" do %>
          <span>Play</span>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col s8">
    <div class="card" id="show_global_details">
      <div class="card-content">
        <ul class="tabs">
          <li class="tab"><a class="active" href="#show_ranking">Ranking</a></li>
          <li class="tab"><a href="#show_activity">Activity</a></li>
        </ul>
        <div class="divider"></div>
        <table class="highlight striped centered">
          <thead>
            <tr>
              <th>HighScore</th>
              <th>Exp</th>
              <th>User</th>
              <th>Title</th>
              <th>Last Played</th>
            </tr>
            <tbody id="list_hightscores">
              <% @highscores.each do |score| %>
                <tr class="highscore_table">
                  <td><%= score.highscore %></td>
                  <td><%= score.category_exp %></td>
                  <td><%= link_to score.user.name, user_path(score.user_id) %></td>
                  <td><%= score.user.title %></td>
                  <td><%= score.user.updated_at.in_time_zone("Singapore").strftime("%e %b %Y %l:%M %p") %></td>
                </tr>
              <% end %>
            </tbody>
          </thead>
        </table>
      </div>
    </div>
  </div>
</div>

<script>

</script>